import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { CardComponent, Navigation } from "@/components";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const { Card, CardContent, CardHeader, CardTitle } = CardComponent;
const { NavMenu, NavMenuList, NavMenuItem, NavMenuLink, navigationMenuTriggerStyle } = Navigation;

export const metadata: Metadata = {
  title: "BADI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={cn(
          "bg-background dark font-sans antialiased",
          inter.variable
        )}>
          <div className="flex h-svh p-2">
            <Card className="rounded-r-none">
              <CardHeader>
                <CardTitle>
                  BADI
                </CardTitle>
              </CardHeader>
              <CardContent className="p-2 min-w-52">
                <NavMenu orientation="vertical">
                  <NavMenuList>
                    <NavMenuItem>
                      <Link href="/" legacyBehavior passHref>
                        <NavMenuLink className={cn(navigationMenuTriggerStyle())}>Home</NavMenuLink>
                      </Link>
                    </NavMenuItem>
                    <NavMenuItem>
                      <Link href="/" legacyBehavior passHref>
                        <NavMenuLink className={cn(navigationMenuTriggerStyle())}>Profile</NavMenuLink>
                      </Link>
                    </NavMenuItem>
                    <NavMenuItem>
                      <Link href="/" legacyBehavior passHref>
                        <NavMenuLink className={cn(navigationMenuTriggerStyle())}>Forum</NavMenuLink>
                      </Link>
                    </NavMenuItem>
                  </NavMenuList>
                </NavMenu>
              </CardContent>
            </Card>
            <Card className="grow rounded-l-none border-l-0">
              <CardHeader />
              <CardContent>
                {children}
              </CardContent>
            </Card>
          </div>
      </body>
    </html>
  );
}
